### PR TITLE
Switch Alderley to incremental updates

### LINKED ISSUE #14: GPL-469 Switch Alderney Park to  incremental updates.
**User story**
GPL-469 | As dev manager (Rich L) I would like the sampler crawler to accept incremental file updates from Alderney Park as well as Milton Keynes as their IT manager (David M) states it now takes too long to download all the data

**Who the primary contacts are for this story**
Rich L
Philip VV
Eduardo MR

**Acceptance criteria**
To be considered successful the solution must allow:
Take incremental updates from AP from week commencing 18th May

**Additional context**
David M (astrazeneca) wrote:  Monday, 18 May 2020 at 22:05

I have uploaded the latest file. This is now an incremental file as it now takes too long to download all the data. I have overlapped slightly with the previous file.

### PR DESCRIPTION
**Pull request by JamesGlover**
Closes #14

Changes proposed in this pull request:

* Sets the Alderley park centre to follow the same
incremental update process as Milton Keynes.
* Adds the ability to ignore files before a certain date, to aid transition to incremental updates
* Adds deduplication of identical rows to handle overlap

### CODE REVIEW

**Comment by JamesGlover** [comment]
I've not touched the behaviour. As best I can tell this means we're regenerating the master file daily, despite file updates only being made weekly.

**Comment by JamesGlover** [comment]
Added an optional merge_start_date filter which will ignore all files predating the start date. This will filter out the initial data dumps. However we will still have duplicate entries for the overlap, while the index should handle this for the database, the master file will still contain them.

**Comment by JamesGlover** [comment]
Actually filtering out the duplicate rows from the master file was simple enough in the end.

**Comment by pjvv** [comment]
I noticed that the GitHub actions are not kicking off and probably because I've never created a PR from a fork so the workflow always started on a push. Could you update the workflow file to trigger on `pull_request` too please? https://help.github.com/en/actions/reference/events-that-trigger-workflows#pull-request-events-for-forked-repositories

**Comment by pjvv** [comment]
```
# Trigger the workflow on push or pull request
on: [push, pull_request]
```

**Comment by JamesGlover** [comment]
Github failing due to the files from the directory being enumerated in a different order in GH actions vs my Mac.

**Pull request merged**
